{
  "patch_root_path": "https://raw.githubusercontent.com/cloudify-cosmo/patchify/master/patch_files/", 
  "patches": [
    {
      "patch_definition_path": "46_local_tasks_restore.json", 
      "patch_description": "Dump/restore support for local tasks.", 
      "patch_files": [
        "46_local_tasks_restore_cloudify_workflows_tasks.py", 
        "46_local_tasks_restore_cloudify_workflows_workflow_context.py"
      ], 
      "patch_hash": "316b313c3bc441abec887e1e0233223c1d0f2021a973a7c5ed2f700dce2ddd42", 
      "patch_id": "46_local_tasks_restore-316b313c3bc441abec887e1e0233223c1d0f2021a973a7c5ed2f700dce2ddd42", 
      "patch_name": "46_local_tasks_restore", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_fix_cfy_status.json", 
      "patch_description": "Allow 'cfy status' command to work even when no Cloudify license is uploaded to the Manager.", 
      "patch_files": [
        "4_6_fix_cfy_status_rest-service_manager_rest_constants.py"
      ], 
      "patch_hash": "07606535edb47639e39dbc9dfe22778127de40eb7d9fbfd075c03e22bc548ea2", 
      "patch_id": "4_6_fix_cfy_status-07606535edb47639e39dbc9dfe22778127de40eb7d9fbfd075c03e22bc548ea2", 
      "patch_name": "4_6_fix_cfy_status", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_fix_hooks_with_plugins.json", 
      "patch_description": "Fix for actionable events (hooks) with plugin implementation.", 
      "patch_files": [
        "4_6_fix_hooks_with_plugins_cloudify_agent_worker.py", 
        "4_6_fix_hooks_with_plugins_cloudify_dispatch.py", 
        "4_6_fix_hooks_with_plugins_cloudify_logs.py"
      ], 
      "patch_hash": "dfe41214d8d5968ce8db07d4f382b7fe84a7222c3c65244e296dc4eb7a7cee5d", 
      "patch_id": "4_6_fix_hooks_with_plugins-dfe41214d8d5968ce8db07d4f382b7fe84a7222c3c65244e296dc4eb7a7cee5d", 
      "patch_name": "4_6_fix_hooks_with_plugins", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_getnodeinstancestate_typo.json", 
      "patch_description": "Fix typo in GetNodeInstanceState task.", 
      "patch_files": [
        "46_getnodeinstancestate_typo_cloudify_workflows_tasks.py"
      ], 
      "patch_hash": "6191046f297c4c0838b7d673064d9f8c5ef7d19fda8c8206c1a97601611bc7e1", 
      "patch_id": "46_getnodeinstancestate_typo-6191046f297c4c0838b7d673064d9f8c5ef7d19fda8c8206c1a97601611bc7e1", 
      "patch_name": "46_getnodeinstancestate_typo", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_improve_failed_snapshot_restore_output.json", 
      "patch_description": "Give more helpful output when a snapshot DB restore fails.", 
      "patch_files": [
        "4_6_improve_failed_snapshot_restore_output_workflows_cloudify_system_workflows_snapshots_postgres.py", 
        "4_6_improve_failed_snapshot_restore_output_workflows_cloudify_system_workflows_snapshots_snapshot_restore.py", 
        "4_6_improve_failed_snapshot_restore_output_workflows_cloudify_system_workflows_snapshots_utils.py"
      ], 
      "patch_hash": "5e7d774790d66846c19d518445dd038234a87594273e9cb174afc747aa6f826f", 
      "patch_id": "4_6_improve_failed_snapshot_restore_output-5e7d774790d66846c19d518445dd038234a87594273e9cb174afc747aa6f826f", 
      "patch_name": "4_6_improve_failed_snapshot_restore_output", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_refresh_ni_scale.json", 
      "patch_description": "Scale workflow: refresh node instances.", 
      "patch_files": [
        "46_refresh_ni_scale_cloudify_plugins_workflows.py", 
        "46_refresh_ni_scale_cloudify_workflows_workflow_context.py"
      ], 
      "patch_hash": "7216e5739778b8afc9db680f2551ddf77a9d31255ac3da02ac4294d94c410f6e", 
      "patch_id": "46_refresh_ni_scale-7216e5739778b8afc9db680f2551ddf77a9d31255ac3da02ac4294d94c410f6e", 
      "patch_name": "46_refresh_ni_scale", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_handle_null_failed_logins_counter.json", 
      "patch_description": "Allow snapshot restore to work with null failed_logins_counter.", 
      "patch_files": [
        "4_6_handle_null_failed_logins_counter_resources_rest-service_cloudify_migrations_versions_1fbd6bf39e84_4_5_to_4_5_5.py"
      ], 
      "patch_hash": "3945c66e2a40c6308d40d4b44797abb18bc07d433576345e243a33ab5687c848", 
      "patch_id": "4_6_handle_null_failed_logins_counter-3945c66e2a40c6308d40d4b44797abb18bc07d433576345e243a33ab5687c848", 
      "patch_name": "4_6_handle_null_failed_logins_counter", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_update_error_param_workflow_failed_trap.json", 
      "patch_description": "update the error parameter in the workflow_failed snmp trap.", 
      "patch_files": [
        "4_6_update_error_param_workflow_failed_trap_cloudify_snmp_snmp_trap.py"
      ], 
      "patch_hash": "d04c3b8c1390097c8c564f1e5b0fa1ebe418e42c74b1d4da48fe2fddd0c06243", 
      "patch_id": "4_6_update_error_param_workflow_failed_trap-d04c3b8c1390097c8c564f1e5b0fa1ebe418e42c74b1d4da48fe2fddd0c06243", 
      "patch_name": "4_6_update_error_param_workflow_failed_trap", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_reset_operations_retry.json", 
      "patch_description": "Don't run retried tasks twice in resume with reset-operations.", 
      "patch_files": [
        "46_reset_operations_retry_cloudify_workflows_tasks.py", 
        "46_reset_operations_retry_manager_rest-service_manager_rest_resource_manager.py"
      ], 
      "patch_hash": "2da2a23b3f6c7271300956678a18802d08ae28b44274be238ebd63c5c440937f", 
      "patch_id": "46_reset_operations_retry-2da2a23b3f6c7271300956678a18802d08ae28b44274be238ebd63c5c440937f", 
      "patch_name": "46_reset_operations_retry", 
      "supports_community": false
    }
  ]
}